server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: client-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/client_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true  # ← ACTIVADO para desarrollo local
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10000
    template:
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 3
    exchange:
      cliente-events: "cliente.events"
    queue:
      cliente-creado: "cliente.creado.queue"
    routing-key:
      cliente-creado: "cliente.creado"

app:
  events:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
  endpoint:
    health:
      show-details: always
      show-components: always
    env:
      enabled: true
    beans:
      enabled: true

logging:
  level:
    com.fal.client_service: DEBUG  # ← DEBUG para desarrollo
    org.springframework: INFO
    org.hibernate: DEBUG  # ← DEBUG para ver SQL
    org.springdoc: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: ./logs/client-service-app.log  # ← Ruta local
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuración específica para desarrollo local
debug: true