spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql-client:3306/client_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    hikari:
      maximum-pool-size: 15
      connection-timeout: 30000
  rabbitmq:
    host: rabbitmq
    connection-timeout: 15000
    template:
      retry:
        max-attempts: 5
        initial-interval: 3000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.bank.client_service: DEBUG
    org.springframework.amqp: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [client-service] [%thread] %-5level %logger{36} - %msg%n"