spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql-account:3306/account_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app_user
    password: userpassword
    hikari:
      maximum-pool-size: 15
      connection-timeout: 30000
  rabbitmq:
    host: rabbitmq
    connection-timeout: 15000
    template:
      retry:
        max-attempts: 5
        initial-interval: 3000
    listener:
      simple:
        retry:
          max-attempts: 5
        default-requeue-rejected: false

app:
  integration:
    account-service:
      url: http://account-service:8081
      timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.bank.account_service: DEBUG
    org.springframework.amqp: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [account-service] [%thread] %-5level %logger{36} - %msg%n"