server:
  port: 8081
  servlet:
    context-path: /api

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql-account:3306/account_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app_user
    password: userpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20


  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10000
    template:
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 3
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3

app:
  integration:
    account-service:
      url: http://account-service:8081
      timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.bank.account_service: DEBUG
    org.springframework.amqp: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [account-service] [%thread] %-5level %logger{36} - %msg%n"